//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeurEmploi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sql11213826Entities : DbContext
    {
        public sql11213826Entities()
            : base("name=sql11213826Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<creneau> creneaux { get; set; }
        public virtual DbSet<departement> departements { get; set; }
        public virtual DbSet<inscription> inscriptions { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<specialite> specialites { get; set; }
        public virtual DbSet<utilisateur> utilisateurs { get; set; }
        public virtual DbSet<emploi> emplois { get; set; }
        public virtual DbSet<salle> salles { get; set; }
    }
}
