//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeurEmploi
{
    using System;
    using System.Collections.Generic;
    
    public partial class module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public module()
        {
            this.inscriptions = new HashSet<inscription>();
            this.emplois = new HashSet<emploi>();
        }
    
        public int id_module { get; set; }
        public string h_cours { get; set; }
        public string h_td { get; set; }
        public string h_tp { get; set; }
        public int vhs { get; set; }
        public string designation { get; set; }
        public int coefficient { get; set; }
        public int id_specialite { get; set; }
        public int niveau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inscription> inscriptions { get; set; }
        public virtual specialite specialite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emploi> emplois { get; set; }
    }
}
